/*
                           /!\ HUMANS BEWARE /!\
=================================================================================
||                                                                             ||
|| THIS FILE IS GENERATED BY MACHINES AND ANY EDITING BY HUMANS IS PROHIBITED! ||
||                                                                             ||
=================================================================================
 */

package lepus.protocol.classes.connection

import lepus.protocol.Method
import lepus.protocol.domains.*
import lepus.protocol.constants.*

enum Requests(classId: ClassId, methodId: MethodId)
    extends Method(classId, methodId) {

  case StartOk(
      clientProperties: PeerProperties,
      mechanism: ShortString,
      response: LongString,
      locale: ShortString
  ) extends Requests(ClassId(10), MethodId(11))

  case SecureOk(response: LongString)
      extends Requests(ClassId(10), MethodId(21))

  case TuneOk(channelMax: Short, frameMax: Int, heartbeat: Short)
      extends Requests(ClassId(10), MethodId(31))

  case Open(virtualHost: Path) extends Requests(ClassId(10), MethodId(40))

  case Close(
      replyCode: ReplyCode,
      replyText: ReplyText,
      classId: ClassId,
      methodId: MethodId
  ) extends Requests(ClassId(10), MethodId(50))

  case CloseOk extends Requests(ClassId(10), MethodId(51))

}
