/*
                           /!\ HUMANS BEWARE /!\
=================================================================================
||                                                                             ||
|| THIS FILE IS GENERATED BY MACHINES AND ANY EDITING BY HUMANS IS PROHIBITED! ||
||                                                                             ||
=================================================================================
 */

package lepus.protocol.classes.connection

import lepus.protocol.Method
import lepus.protocol.domains.*
import lepus.protocol.constants.*

enum Responses(classId: ClassId, methodId: MethodId)
    extends Method(classId, methodId) {

  case Start(
      versionMajor: Byte,
      versionMinor: Byte,
      serverProperties: PeerProperties,
      mechanisms: LongString,
      locales: LongString
  ) extends Responses(ClassId(10), MethodId(10))

  case Secure(challenge: LongString)
      extends Responses(ClassId(10), MethodId(20))

  case Tune(channelMax: Short, frameMax: Int, heartbeat: Short)
      extends Responses(ClassId(10), MethodId(30))

  case OpenOk() extends Responses(ClassId(10), MethodId(41))

  case Close(
      replyCode: ReplyCode,
      replyText: ReplyText,
      classId: ClassId,
      methodId: MethodId
  ) extends Responses(ClassId(10), MethodId(50))

  case CloseOk extends Responses(ClassId(10), MethodId(51))

}
