/*
                           /!\ HUMANS BEWARE /!\
=================================================================================
||                                                                             ||
|| THIS FILE IS GENERATED BY MACHINES AND ANY EDITING BY HUMANS IS PROHIBITED! ||
||                                                                             ||
=================================================================================
 */

package lepus.codecs

import lepus.protocol.Method
import lepus.protocol.classes.*
import lepus.protocol.constants.*
import lepus.protocol.domains.*
import org.scalacheck.Arbitrary
import org.scalacheck.Gen
import ArbitraryDomains.given

object AllClassesDataGenerator {

  val methods: Gen[Method] = Gen.oneOf(
    ConnectionDataGenerator.classGen,
    ChannelDataGenerator.classGen,
    ExchangeDataGenerator.classGen,
    QueueDataGenerator.classGen,
    BasicDataGenerator.classGen,
    TxDataGenerator.classGen,
    ConfirmDataGenerator.classGen
  )

}
