/*
                           /!\ HUMANS BEWARE /!\
=================================================================================
||                                                                             ||
|| THIS FILE IS GENERATED BY MACHINES AND ANY EDITING BY HUMANS IS PROHIBITED! ||
||                                                                             ||
=================================================================================
 */

package lepus.codecs

import lepus.protocol.Method
import lepus.protocol.classes.*
import lepus.protocol.constants.*
import lepus.protocol.domains.*
import org.scalacheck.Arbitrary
import org.scalacheck.Gen
import ArbitraryDomains.given

object ExchangeDataGenerator {

  val declareGen: Gen[ExchangeClass.Declare] =
    for {
      arg0 <- Arbitrary.arbitrary[ExchangeName]
      arg1 <- Arbitrary.arbitrary[ShortString]
      arg2 <- Arbitrary.arbitrary[Boolean]
      arg3 <- Arbitrary.arbitrary[Boolean]
      arg4 <- Arbitrary.arbitrary[Boolean]
      arg5 <- Arbitrary.arbitrary[Boolean]
      arg6 <- Arbitrary.arbitrary[NoWait]
      arg7 <- Arbitrary.arbitrary[FieldTable]
    } yield ExchangeClass.Declare(
      arg0,
      arg1,
      arg2,
      arg3,
      arg4,
      arg5,
      arg6,
      arg7
    )

  given Arbitrary[ExchangeClass.Declare] = Arbitrary(declareGen)

  val declareOkGen: Gen[ExchangeClass.DeclareOk.type] =
    Gen.const(ExchangeClass.DeclareOk)

  given Arbitrary[ExchangeClass.DeclareOk.type] = Arbitrary(declareOkGen)

  val deleteGen: Gen[ExchangeClass.Delete] =
    for {
      arg0 <- Arbitrary.arbitrary[ExchangeName]
      arg1 <- Arbitrary.arbitrary[Boolean]
      arg2 <- Arbitrary.arbitrary[NoWait]
    } yield ExchangeClass.Delete(arg0, arg1, arg2)

  given Arbitrary[ExchangeClass.Delete] = Arbitrary(deleteGen)

  val deleteOkGen: Gen[ExchangeClass.DeleteOk.type] =
    Gen.const(ExchangeClass.DeleteOk)

  given Arbitrary[ExchangeClass.DeleteOk.type] = Arbitrary(deleteOkGen)

  val bindGen: Gen[ExchangeClass.Bind] =
    for {
      arg0 <- Arbitrary.arbitrary[ExchangeName]
      arg1 <- Arbitrary.arbitrary[ExchangeName]
      arg2 <- Arbitrary.arbitrary[ShortString]
      arg3 <- Arbitrary.arbitrary[NoWait]
      arg4 <- Arbitrary.arbitrary[FieldTable]
    } yield ExchangeClass.Bind(arg0, arg1, arg2, arg3, arg4)

  given Arbitrary[ExchangeClass.Bind] = Arbitrary(bindGen)

  val bindOkGen: Gen[ExchangeClass.BindOk.type] =
    Gen.const(ExchangeClass.BindOk)

  given Arbitrary[ExchangeClass.BindOk.type] = Arbitrary(bindOkGen)

  val unbindGen: Gen[ExchangeClass.Unbind] =
    for {
      arg0 <- Arbitrary.arbitrary[ExchangeName]
      arg1 <- Arbitrary.arbitrary[ExchangeName]
      arg2 <- Arbitrary.arbitrary[ShortString]
      arg3 <- Arbitrary.arbitrary[NoWait]
      arg4 <- Arbitrary.arbitrary[FieldTable]
    } yield ExchangeClass.Unbind(arg0, arg1, arg2, arg3, arg4)

  given Arbitrary[ExchangeClass.Unbind] = Arbitrary(unbindGen)

  val unbindOkGen: Gen[ExchangeClass.UnbindOk.type] =
    Gen.const(ExchangeClass.UnbindOk)

  given Arbitrary[ExchangeClass.UnbindOk.type] = Arbitrary(unbindOkGen)

  val classGen: Gen[ExchangeClass] = Gen.oneOf(
    declareGen,
    declareOkGen,
    deleteGen,
    deleteOkGen,
    bindGen,
    bindOkGen,
    unbindGen,
    unbindOkGen
  )

  given Arbitrary[ExchangeClass] = Arbitrary(classGen)

}
