/*
                           /!\ HUMANS BEWARE /!\
=================================================================================
||                                                                             ||
|| THIS FILE IS GENERATED BY MACHINES AND ANY EDITING BY HUMANS IS PROHIBITED! ||
||                                                                             ||
=================================================================================
 */

package lepus.protocol.classes.exchange

import lepus.protocol.Method
import lepus.protocol.domains.*
import lepus.protocol.constants.*

enum Requests(classId: ClassId, methodId: MethodId)
    extends Method(classId, methodId) {

  case Declare(
      exchange: ExchangeName,
      `type`: ShortString,
      passive: Boolean,
      durable: Boolean,
      noWait: NoWait,
      arguments: FieldTable
  ) extends Requests(ClassId(40), MethodId(10))

  case Delete(exchange: ExchangeName, ifUnused: Boolean, noWait: NoWait)
      extends Requests(ClassId(40), MethodId(20))

}
