/*
 * Copyright 2021 Hossein Naderi
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package lepus.protocol.gen

import cats.effect.IO
import fs2.Pipe
import fs2.Stream
import fs2.io.file.Files
import fs2.io.file.Path
import fs2.text.utf8

type Lines = Stream[IO, String]
type FileGen = Pipe[IO, String, Nothing]

object Helpers {
  private val genWarn: String = """
/*
                           /!\ HUMANS BEWARE /!\
=================================================================================
||                                                                             ||
|| THIS FILE IS GENERATED BY MACHINES AND ANY EDITING BY HUMANS IS PROHIBITED! ||
||                                                                             ||
=================================================================================
*/
"""
  def srcFile(module: String, out: Path): FileGen =
    file(module, out, isMain = true)

  def testFile(module: String, out: Path): FileGen =
    file(module, out, isMain = false)

  def file(module: String, out: Path, isMain: Boolean): FileGen = lines =>
    val subDir = if isMain then "main" else "test"
    val base = Path(s"modules/$module/src/$subDir/scala")
    (Stream(genWarn) ++ lines)
      .intersperse("\n")
      .through(utf8.encode)
      .through(
        Files[IO].writeAll(base / out)
      )

  private val namePattern = "\\W*\\b(\\w)".r
  def idName(str: String): String =
    namePattern.replaceAllIn(str, m => m.group(1).toUpperCase)
  def valName(str: String): String = {
    val id = idName(str)
    id.headOption.map(_.toLower).map(id.tail.prepended).getOrElse(id)
  }

  def comment(str: String): String = s"/**\n$str\n */"

  def obj(name: String)(lines: Lines): Lines =
    (Stream(s"object ${idName(name)} {") ++ lines ++ Stream("}"))

  def obj(name: String)(lines: Seq[String]): Lines =
    obj(name)(Stream.emits(lines))

  def headers(hs: String*): Lines = Stream.emits(hs)
}
