/*
                           /!\ HUMANS BEWARE /!\
=================================================================================
||                                                                             ||
|| THIS FILE IS GENERATED BY MACHINES AND ANY EDITING BY HUMANS IS PROHIBITED! ||
||                                                                             ||
=================================================================================
 */

package lepus.client.codecs

import lepus.protocol.*
import lepus.protocol.domains.*
import lepus.protocol.classes.*
import lepus.protocol.classes.ChannelClass.*
import lepus.protocol.constants.*
import lepus.client.codecs.DomainCodecs.*
import scodec.{Codec, Encoder, Decoder}
import scodec.codecs.*

object ChannelCodecs {

  private val openCodec: Codec[Open.type] =
    (emptyShortString) ~> provide(Open)
      .withContext("open method")

  private val openOkCodec: Codec[OpenOk.type] =
    (emptyLongString) ~> provide(OpenOk)
      .withContext("openOk method")

  private val flowCodec: Codec[Flow] =
    (reverseByteAligned(7, bool))
      .as[Flow]
      .withContext("flow method")

  private val flowOkCodec: Codec[FlowOk] =
    (reverseByteAligned(7, bool))
      .as[FlowOk]
      .withContext("flowOk method")

  private val closeCodec: Codec[Close] =
    (replyCode :: replyText :: classId :: methodId)
      .as[Close]
      .withContext("close method")

  private val closeOkCodec: Codec[CloseOk.type] =
    provide(CloseOk)
      .withContext("closeOk method")

  val all: Codec[ChannelClass] =
    discriminated[ChannelClass]
      .by(methodId)
      .subcaseP[Open.type](MethodId(10)) { case m: Open.type => m }(openCodec)
      .subcaseP[OpenOk.type](MethodId(11)) { case m: OpenOk.type => m }(
        openOkCodec
      )
      .subcaseP[Flow](MethodId(20)) { case m: Flow => m }(flowCodec)
      .subcaseP[FlowOk](MethodId(21)) { case m: FlowOk => m }(flowOkCodec)
      .subcaseP[Close](MethodId(40)) { case m: Close => m }(closeCodec)
      .subcaseP[CloseOk.type](MethodId(41)) { case m: CloseOk.type => m }(
        closeOkCodec
      )
      .withContext("channel methods")

}
