/*
                           /!\ HUMANS BEWARE /!\
=================================================================================
||                                                                             ||
|| THIS FILE IS GENERATED BY MACHINES AND ANY EDITING BY HUMANS IS PROHIBITED! ||
||                                                                             ||
=================================================================================
 */

package lepus.client.codecs

import lepus.protocol.Method
import lepus.protocol.domains.ClassId
import lepus.protocol.classes.*
import lepus.client.codecs.DomainCodecs.classId
import scodec.Codec
import scodec.codecs.discriminated

object MethodCodec {

  val all: Codec[Method] = discriminated
    .by(classId)
    .typecase(ClassId(10), ConnectionCodecs.all)
    .typecase(ClassId(20), ChannelCodecs.all)
    .typecase(ClassId(40), ExchangeCodecs.all)
    .typecase(ClassId(50), QueueCodecs.all)
    .typecase(ClassId(60), BasicCodecs.all)
    .typecase(ClassId(90), TxCodecs.all)
    .typecase(ClassId(85), ConfirmCodecs.all)
    .withContext("Method codecs")

}
