addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.6")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.10.1")
addSbtPlugin("org.typelevel" % "sbt-typelevel" % "0.4.13")
addSbtPlugin("org.typelevel" % "sbt-typelevel-site" % "0.4.13")
addSbtPlugin("org.typelevel" % "sbt-typelevel-github-actions" % "0.4.13")
