addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.5.0")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.10.4")
addSbtPlugin("org.typelevel" % "sbt-typelevel" % "0.4.16")
addSbtPlugin("org.typelevel" % "sbt-typelevel-site" % "0.4.16")
addSbtPlugin("org.typelevel" % "sbt-typelevel-github-actions" % "0.4.16")
