/*
                           /!\ HUMANS BEWARE /!\
=================================================================================
||                                                                             ||
|| THIS FILE IS GENERATED BY MACHINES AND ANY EDITING BY HUMANS IS PROHIBITED! ||
||                                                                             ||
=================================================================================
 */

package lepus.protocol.classes.queue

import lepus.protocol.Method
import lepus.protocol.domains.*
import lepus.protocol.constants.*

enum Responses(classId: ClassId, methodId: MethodId)
    extends Method(classId, methodId) {

  case DeclareOk(
      queue: QueueName,
      messageCount: MessageCount,
      consumerCount: Int
  ) extends Responses(ClassId(50), MethodId(11))

  case BindOk extends Responses(ClassId(50), MethodId(21))

  case UnbindOk extends Responses(ClassId(50), MethodId(51))

  case PurgeOk(messageCount: MessageCount)
      extends Responses(ClassId(50), MethodId(31))

  case DeleteOk(messageCount: MessageCount)
      extends Responses(ClassId(50), MethodId(41))

}
