
/*
                           /!\ HUMANS BEWARE /!\
=================================================================================
||                                                                             ||
|| THIS FILE IS GENERATED BY MACHINES AND ANY EDITING BY HUMANS IS PROHIBITED! ||
||                                                                             ||
=================================================================================
*/

package lepus.client.gen
enum Basic {
  case Qos
  case QosOk
  case Consume
  case ConsumeOk
  case Cancel
  case CancelOk
  case Publish
  case Return
  case Deliver
  case Get
  case GetOk
  case GetEmpty
  case Ack
  case Reject
  case RecoverAsync
  case Recover
  case RecoverOk
}