
/*
                           /!\ HUMANS BEWARE /!\
=================================================================================
||                                                                             ||
|| THIS FILE IS GENERATED BY MACHINES AND ANY EDITING BY HUMANS IS PROHIBITED! ||
||                                                                             ||
=================================================================================
*/

package lepus.client.gen
enum Channel {
  case Open
  case OpenOk
  case Flow
  case FlowOk
  case Close
  case CloseOk
}