
/*
                           /!\ HUMANS BEWARE /!\
=================================================================================
||                                                                             ||
|| THIS FILE IS GENERATED BY MACHINES AND ANY EDITING BY HUMANS IS PROHIBITED! ||
||                                                                             ||
=================================================================================
*/

package lepus.client.gen
enum Connection {
  case Start
  case StartOk
  case Secure
  case SecureOk
  case Tune
  case TuneOk
  case Open
  case OpenOk
  case Close
  case CloseOk
}