
/*
                           /!\ HUMANS BEWARE /!\
=================================================================================
||                                                                             ||
|| THIS FILE IS GENERATED BY MACHINES AND ANY EDITING BY HUMANS IS PROHIBITED! ||
||                                                                             ||
=================================================================================
*/

package lepus.client.gen
enum Exchange {
  case Declare
  case DeclareOk
  case Delete
  case DeleteOk
}