
/*
                           /!\ HUMANS BEWARE /!\
=================================================================================
||                                                                             ||
|| THIS FILE IS GENERATED BY MACHINES AND ANY EDITING BY HUMANS IS PROHIBITED! ||
||                                                                             ||
=================================================================================
*/

package lepus.client.gen
enum Queue {
  case Declare
  case DeclareOk
  case Bind
  case BindOk
  case Unbind
  case UnbindOk
  case Purge
  case PurgeOk
  case Delete
  case DeleteOk
}