
/*
                           /!\ HUMANS BEWARE /!\
=================================================================================
||                                                                             ||
|| THIS FILE IS GENERATED BY MACHINES AND ANY EDITING BY HUMANS IS PROHIBITED! ||
||                                                                             ||
=================================================================================
*/

package lepus.client.gen
enum Tx {
  case Select
  case SelectOk
  case Commit
  case CommitOk
  case Rollback
  case RollbackOk
}