/*
                           /!\ HUMANS BEWARE /!\
=================================================================================
||                                                                             ||
|| THIS FILE IS GENERATED BY MACHINES AND ANY EDITING BY HUMANS IS PROHIBITED! ||
||                                                                             ||
=================================================================================
 */

package lepus.protocol.classes

import lepus.protocol.*
import lepus.protocol.domains.*
import lepus.protocol.constants.*

enum TxClass(methodId: MethodId)
    extends Class(ClassId(90))
    with Method(methodId) {

  case Select extends TxClass(MethodId(10)) with Response

  case SelectOk extends TxClass(MethodId(11)) with Request

  case Commit extends TxClass(MethodId(20)) with Response

  case CommitOk extends TxClass(MethodId(21)) with Request

  case Rollback extends TxClass(MethodId(30)) with Response

  case RollbackOk extends TxClass(MethodId(31)) with Request

}
