/*
                           /!\ HUMANS BEWARE /!\
=================================================================================
||                                                                             ||
|| THIS FILE IS GENERATED BY MACHINES AND ANY EDITING BY HUMANS IS PROHIBITED! ||
||                                                                             ||
=================================================================================
 */

package lepus.protocol.classes.tx

import lepus.protocol.Method
import lepus.protocol.domains.*
import lepus.protocol.constants.*

enum Requests(classId: ClassId, methodId: MethodId)
    extends Method(classId, methodId) {

  case Select extends Requests(ClassId(90), MethodId(10))

  case Commit extends Requests(ClassId(90), MethodId(20))

  case Rollback extends Requests(ClassId(90), MethodId(30))

}
