/*
                           /!\ HUMANS BEWARE /!\
=================================================================================
||                                                                             ||
|| THIS FILE IS GENERATED BY MACHINES AND ANY EDITING BY HUMANS IS PROHIBITED! ||
||                                                                             ||
=================================================================================
 */

package lepus.protocol.classes.tx

import lepus.protocol.Method
import lepus.protocol.domains.*
import lepus.protocol.constants.*

enum Responses(classId: ClassId, methodId: MethodId)
    extends Method(classId, methodId) {

  case SelectOk extends Responses(ClassId(90), MethodId(11))

  case CommitOk extends Responses(ClassId(90), MethodId(21))

  case RollbackOk extends Responses(ClassId(90), MethodId(31))

}
