/*
                           /!\ HUMANS BEWARE /!\
=================================================================================
||                                                                             ||
|| THIS FILE IS GENERATED BY MACHINES AND ANY EDITING BY HUMANS IS PROHIBITED! ||
||                                                                             ||
=================================================================================
 */

package lepus.protocol.classes

import lepus.protocol.*
import lepus.protocol.domains.*
import lepus.protocol.constants.*

enum ConfirmClass(methodId: MethodId)
    extends Class(ClassId(85))
    with Method(methodId) {

  case Select(nowait: NoWait) extends ConfirmClass(MethodId(10)) with Response

  case SelectOk extends ConfirmClass(MethodId(11)) with Request

}
