/*
                           /!\ HUMANS BEWARE /!\
=================================================================================
||                                                                             ||
|| THIS FILE IS GENERATED BY MACHINES AND ANY EDITING BY HUMANS IS PROHIBITED! ||
||                                                                             ||
=================================================================================
 */

package lepus.protocol.classes

import lepus.protocol.*
import lepus.protocol.domains.*
import lepus.protocol.constants.*

enum ChannelClass(methodId: MethodId)
    extends Class(ClassId(20))
    with Method(methodId) {

  case Open extends ChannelClass(MethodId(10)) with Response

  case OpenOk extends ChannelClass(MethodId(11)) with Request

  case Flow(active: Boolean)
      extends ChannelClass(MethodId(20))
      with Response
      with Request

  case FlowOk(active: Boolean)
      extends ChannelClass(MethodId(21))
      with Response
      with Request

  case Close(
      replyCode: ReplyCode,
      replyText: ReplyText,
      classId: ClassId,
      methodId: MethodId
  ) extends ChannelClass(MethodId(40)) with Response with Request

  case CloseOk extends ChannelClass(MethodId(41)) with Response with Request

}
