/*
                           /!\ HUMANS BEWARE /!\
=================================================================================
||                                                                             ||
|| THIS FILE IS GENERATED BY MACHINES AND ANY EDITING BY HUMANS IS PROHIBITED! ||
||                                                                             ||
=================================================================================
 */

package lepus.protocol.classes.channel

import lepus.protocol.Method
import lepus.protocol.domains.*
import lepus.protocol.constants.*

enum Requests(classId: ClassId, methodId: MethodId)
    extends Method(classId, methodId) {

  case Open() extends Requests(ClassId(20), MethodId(10))

  case Flow(active: Boolean) extends Requests(ClassId(20), MethodId(20))

  case FlowOk(active: Boolean) extends Requests(ClassId(20), MethodId(21))

  case Close(
      replyCode: ReplyCode,
      replyText: ReplyText,
      classId: ClassId,
      methodId: MethodId
  ) extends Requests(ClassId(20), MethodId(40))

  case CloseOk extends Requests(ClassId(20), MethodId(41))

}
